Add --delete-profile option

diff --git a/nixos-alter b/nixos-alter
--- a/nixos-alter
+++ b/nixos-alter
@@ -9,6 +9,8 @@ nixos-alter
 -m --modify-profile         Modify the profile to be the result configuration
 -l --link                   Create a symlink in the current directory. Default name of link is ./result
 
+-D --delete-profile         Delete the profile
+
 -o --out <path>             Sets the path the symlink generated by --link is located at. Implies --link
 -P --profile <path>         Path to the profile to use. Defaults to /nix/var/nix/profiles/system
 -p --profile-name <name>    Name of the profile to use. Mostly equivalent to --profile /nix/var/nix/profiles/system-profiles/<name>
@@ -33,6 +35,8 @@ nixos-alter
    --list-generations       List all generations
    --help                   Display usage information
 
+--boot, --activate, --modify-profile, and --link conflict with --delete-profile.
+
 Note that, currently, --profile and --profile-name must occur before --list-generations, --generation or --current-generation.
 
 Abbreviations:
@@ -50,6 +54,7 @@ boot=0
 activate=0
 modify=0
 link=0
+delete=0
 out=$PWD/result
 profile=/nix/var/nix/profiles/system
 pathToConfig=
@@ -61,7 +66,7 @@ while [ "$#" -gt 0 ]; do
   arg="$1"; shift 1
 
   # Handling of one-letter args
-  if [[ "$arg" =~ ^-(b|a|m|l|o|p|P|I|E|j|K|k|g) ]]; then
+  if [[ "$arg" =~ ^-(b|a|m|l|D|o|p|P|I|E|j|K|k|g) ]]; then
     arg=${arg:1} # Remove the dash
 
     newArgs=()
@@ -82,6 +87,9 @@ while [ "$#" -gt 0 ]; do
           ;;
         l)
           newArgs+=(--link)
+          ;;
+        D)
+          newArgs+=(--delete)
           ;;
         o)
           if [ -n "$arg" ]; then
@@ -183,6 +191,9 @@ while [ "$#" -gt 0 ]; do
       ;;
     --link)
       link=1
+      ;;
+    --delete)
+      delete=1
       ;;
     --out)
       if [ -z "$1" ]; then
@@ -288,6 +299,16 @@ while [ "$#" -gt 0 ]; do
       ;;
   esac
 done
+
+if [ "$delete" -eq 1 ]; then
+  if [ "$boot" -eq 1 ] || [ "$activate" -eq 1 ] || [ "$modify" -eq 1 ] || [ "$link" -eq 1 ]; then
+    echo "error: Can't use --boot, --activate, --modify-profile, or --link with --delete-profile" >&2
+    exit 1
+  fi
+
+  rm "$profile" "$profile"-*-link
+  exit 0
+fi
 
 if [ "$boot" -eq 0 ] && [ "$activate" -eq 0 ] && [ "$modify" -eq 0 ] && [ "$link" -eq 0 ]; then
   echo "warning: None of --boot, --activate, --modify-profile, and --link specified" >&2
