Add --build-vm and related options

diff --git a/nixos-alter b/nixos-alter
--- a/nixos-alter
+++ b/nixos-alter
@@ -8,10 +8,11 @@ nixos-alter
 -a --activate               Activate
 -m --modify-profile         Modify the profile to be the result configuration
 -l --link                   Create a symlink in the current directory. Default name of link is ./result
+   --force                  Build even without any of the above options
+   --build-vm               Build the system as a virtual machine. Conflicts with --boot, --activate, and --modify-profile
+   --include-bootloader     Build the virtual machine with a boot loader
 
 -D --delete-profile         Delete the profile
-
-   --force                  Build even without any of the above options
 
 -o --out <path>             Sets the path the symlink generated by --link is located at. Implies --link
 -P --profile <path>         Path to the profile to use. Defaults to /nix/var/nix/profiles/system
@@ -37,27 +38,35 @@ nixos-alter
    --list-generations       List all generations
    --help                   Display usage information
 
---boot, --activate, --modify-profile, and --link conflict with --delete-profile.
+The first two groups of flags conflict with each other.
 
 Note that, currently, --profile and --profile-name must occur before --list-generations.
 
 Abbreviations:
 
-test          --activate            -a
-boot          --boot                -b
-switch        --boot --activate     -ba
-build         --link                -l
+test                     --activate                             -a
+boot                     --boot                                 -b
+switch                   --boot --activate                      -ba
+build                    --link                                 -l
+build-vm                 --build-vm --link
+build-vm-with-bootloader --build-vm --include-bootloader --link
 EOF
   exit 1
 }
 
 extraBuildArgs=()
+
+# Category 1
 boot=0
 activate=0
 modify=0
 link=0
-delete=0
 force=0
+build_vm=0
+include_bootloader=0
+# Category 2
+delete=0
+
 out=$PWD/result
 profile=/nix/var/nix/profiles/system
 pathToConfig=
@@ -177,7 +186,7 @@ while [ "$#" -gt 0 ]; do
     set -- "${newArgs[@]}" "$@"
 
     arg="$1"; shift 1
-  elif [[ "$arg" =~ ^(test|boot|switch|build)$ ]]; then
+  elif [[ "$arg" =~ ^(test|boot|switch|build|build-vm|build-vm-with-bootloader)$ ]]; then
     case "$arg" in
       test)
         set -- --activate "$@"
@@ -190,6 +199,12 @@ while [ "$#" -gt 0 ]; do
         ;;
       build)
         set -- --link "$@"
+        ;;
+      build-vm)
+        set -- --build-vm --link "$@"
+        ;;
+      build-vm-with-bootloader)
+        set -- --build-vm --include-bootloader --link "$@"
         ;;
     esac
 
@@ -210,11 +225,18 @@ while [ "$#" -gt 0 ]; do
     --link)
       link=1
       ;;
-    --delete-profile)
-      delete=1
-      ;;
     --force)
       force=1
+      ;;
+    --build-vm)
+      build_vm=1
+      ;;
+    --include-bootloader)
+      build_vm=1
+      include_bootloader=1
+      ;;
+    --delete-profile)
+      delete=1
       ;;
     --out)
       if [ -z "$1" ]; then
@@ -326,91 +348,105 @@ while [ "$#" -gt 0 ]; do
   esac
 done
 
-if [ "$delete" -eq 1 ]; then
-  if [ "$boot" -eq 1 ] || [ "$activate" -eq 1 ] || [ "$modify" -eq 1 ] || [ "$link" -eq 1 ]; then
-    echo "error: Can't use --boot, --activate, --modify-profile, or --link with --delete-profile" >&2
-    exit 1
-  fi
+# There's probably a better way to do this
+[ "$boot" -eq 1 ] || [ "$activate" -eq 1 ] || [ "$modify" -eq 1 ] || [ "$link" -eq 1 ] || [ "$force" -eq 1 ] || [ "$build_vm" -eq 1 ] || [ "$include_bootloader" -eq 1 ] && category_1=1 || category_1=0
+[ "$delete" -eq 1 ]                                                                                                                                                      && category_2=1 || category_2=0
 
-  rm "$profile" "$profile"-*-link
-  exit 0
-fi
-
-if [ "$boot" -eq 0 ] && [ "$activate" -eq 0 ] && [ "$modify" -eq 0 ] && [ "$link" -eq 0 ] && ! [ "$force" -eq 1 ]; then
-  echo "error: None of --boot, --activate, --modify-profile, --link, and --delete-profile specified. Set --force to ignore. Run 'nixos-alter --help' for more information" >&2
+if [ $((category_1 + category_2)) -ne 1 ]; then
+  echo "error: Exactly one of the first two groups of flags expected" >&2
   exit 1
 fi
 
-if [ -n "$generation" ]; then
-  pathToConfig=$(realpath "$profile-$generation-link")
-fi
-if [ -z "$pathToConfig" ]; then
-  if [ "$rebuild_nix" -eq 1 ]; then
-    echo "Building Nix..." >&2
+# build_attr <attr> <id>
+build_attr() {
+  if [ "$old_nix" -eq 1 ]; then
+    nix-build '<nixpkgs/nixos>' -A "$1" "${extraBuildArgs[@]}"
 
-    if [ "$old_nix" -eq 1 ]; then
-      pathToNix="$(nix-build '<nixpkgs/nixos>' -A config.nix.package.out "${extraBuildArgs[@]}")"
+    if [ $? -eq 1 ]; then
+      exit 1
+    fi
+  else
+    nix build -f '<nixpkgs/nixos>' "$1" "${extraBuildArgs[@]}" --out-link "$tmpdir/$2"
+    if [ $? -eq 1 ]; then
+      exit 1
+    fi
+    realpath "$tmpdir/$2"
+  fi
+}
 
+if [ "$category_1" -eq 1 ]; then
+  # Category 1
+  if [ "$build_vm" -eq 1 ]; then
+    if [ "$boot" -eq 1 ] || [ "$activate" -eq 1 ] || [ "$modify" -eq 1 ]; then
+      echo "Error: --build-vm cannot be used with --boot, --activate, and --modify-profile" >&2
+      exit 1
+    fi
+  fi
+
+  if [ -n "$generation" ]; then
+    pathToConfig=$(realpath "$profile-$generation-link")
+  fi
+  if [ -z "$pathToConfig" ]; then
+    if [ "$rebuild_nix" -eq 1 ]; then
+      echo "Building Nix..." >&2
+
+      pathToNix="$(build_attr config.nix.package.out nix)"
       if [ $? -eq 1 ]; then
         echo "Something went wrong while building Nix." >&2
+        exit 1
+      fi
+
+      PATH="$pathToNix/bin:$PATH"
+    fi
+
+    if [ "$build_vm" -eq 1 ]; then
+      echo "Building the virtual machine..." >&2
+
+      [ "$include_bootloader" -eq 1 ] && attr=vmWithBootLoader || attr=vm
+      pathToConfig="$(build_attr "$attr" vm)"
+      if [ $? -eq 1 ]; then
+        echo "Something went wrong while building the virtual machine." >&2
         exit 1
       fi
     else
-      nix build -f '<nixpkgs/nixos>' config.nix.package.out "${extraBuildArgs[@]}" --out-link "$tmpdir/nix"
+      echo "Building the system configuration..." >&2
+
+      pathToConfig="$(build_attr system system)"
       if [ $? -eq 1 ]; then
-        echo "Something went wrong while building Nix." >&2
+        echo "Something went wrong while building the system configuration." >&2
         exit 1
       fi
-      pathToNix="$(realpath "$tmpdir/nix")"
-    fi
-
-    PATH="$pathToNix/bin:$PATH"
-  fi
-
-  echo "Building the system configuration..." >&2
-
-  if [ "$old_nix" -eq 1 ]; then
-    pathToConfig="$(nix-build '<nixpkgs/nixos>' --no-out-link -A system "${extraBuildArgs[@]}")"
-
-    if [ $? -eq 1 ]; then
-      echo "Something went wrong while building the system configuration." >&2
-      exit 1
     fi
   else
-    nix build -f '<nixpkgs/nixos>' --out-link "$tmpdir/system" system "${extraBuildArgs[@]}"
-    if [ $? -eq 1 ]; then
-      echo "Something went wrong while building the system configuration." >&2
-      exit 1
-    fi
-    pathToConfig="$(realpath "$tmpdir/system")"
+    echo "Skipping rebuild" >&2
   fi
-else
-  echo "Skipping rebuild" >&2
-fi
 
-if [ "$link" -eq 1 ]; then
-  nix-store --realise "$pathToConfig" --add-root "$out" --indirect
-elif [ "$modify" -eq 1 ] || [ "$boot" -eq 1 ]; then
-  echo "$profile"
-else
-  echo "$pathToConfig"
-fi 
-# Note that we don't allow --boot without --modify-profile
-if [ "$modify" -eq 1 ] || [ "$boot" -eq 1 ]; then
-  if [ -n "$generation" ]; then
-    nix-env -p "$profile" --switch-generation "$generation"
+  if [ "$link" -eq 1 ]; then
+    nix-store --realise "$pathToConfig" --add-root "$out" --indirect
+  elif [ "$modify" -eq 1 ] || [ "$boot" -eq 1 ]; then
+    echo "$profile"
   else
-    nix-env -p "$profile" --set "$pathToConfig"
+    echo "$pathToConfig"
   fi
-fi
-if [ "$boot" -eq 1 ]; then
-  if ! [[ "$profile" =~ ^/nix/var/nix/profiles ]]; then
-    echo "warning: It looks like you're trying to set the boot default to a profile"    >&2
-    echo "         that is not in /nix/var/nix/profiles. This is not something you're"  >&2
-    echo "         supposed to do."                                                     >&2
+  # Note that we don't allow --boot without --modify-profile
+  if [ "$modify" -eq 1 ] || [ "$boot" -eq 1 ]; then
+    if [ -n "$generation" ]; then
+      nix-env -p "$profile" --switch-generation "$generation"
+    else
+      nix-env -p "$profile" --set "$pathToConfig"
+    fi
   fi
-  "$pathToConfig/bin/switch-to-configuration" boot
-fi
-if [ "$activate" -eq 1 ]; then
-  "$pathToConfig/bin/switch-to-configuration" test
+  if [ "$boot" -eq 1 ]; then
+    if ! [[ "$profile" =~ ^/nix/var/nix/profiles ]]; then
+      echo "warning: It looks like you're trying to set the boot default to a profile"    >&2
+      echo "         that is not in /nix/var/nix/profiles. This is not something you're"  >&2
+      echo "         supposed to do."                                                     >&2
+    fi
+    "$pathToConfig/bin/switch-to-configuration" boot
+  fi
+  if [ "$activate" -eq 1 ]; then
+    "$pathToConfig/bin/switch-to-configuration" test
+  fi
+elif [ "$category_2" -eq 1 ]; then
+  rm "$profile" "$profile"-*-link
 fi
