Make "You need to specify at least one of -baml" an error again, and add -D to the error message

diff --git a/nixos-alter b/nixos-alter
--- a/nixos-alter
+++ b/nixos-alter
@@ -11,6 +11,8 @@ nixos-alter
 
 -D --delete-profile         Delete the profile
 
+   --force                  Build even without any of the above options
+
 -o --out <path>             Sets the path the symlink generated by --link is located at. Implies --link
 -P --profile <path>         Path to the profile to use. Defaults to /nix/var/nix/profiles/system
 -p --profile-name <name>    Name of the profile to use. Mostly equivalent to --profile /nix/var/nix/profiles/system-profiles/<name>
@@ -56,6 +58,7 @@ activate=0
 modify=0
 link=0
 delete=0
+force=0
 out=$PWD/result
 profile=/nix/var/nix/profiles/system
 pathToConfig=
@@ -90,7 +93,7 @@ while [ "$#" -gt 0 ]; do
           newArgs+=(--link)
           ;;
         D)
-          newArgs+=(--delete)
+          newArgs+=(--delete-profile)
           ;;
         o)
           if [ -n "$arg" ]; then
@@ -201,12 +204,15 @@ while [ "$#" -gt 0 ]; do
     --link)
       link=1
       ;;
-    --delete)
+    --delete-profile)
       delete=1
+      ;;
+    --force)
+      force=1
       ;;
     --out)
       if [ -z "$1" ]; then
-        echo "$0: '--out' requires an argument" >&2
+        echo "nixos-alter: '--out' requires an argument" >&2
         exit 1
       fi
 
@@ -217,7 +223,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --profile)
       if [ -z "$1" ]; then
-        echo "$0: '--profile' requires an argument" >&2
+        echo "nixos-alter: '--profile' requires an argument" >&2
         exit 1
       fi
       if [ "$1" != system ]; then
@@ -227,7 +233,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --profile-name)
       if [ -z "$1" ]; then
-        echo "$0: '--profile-name' requires an argument" >&2
+        echo "nixos-alter: '--profile-name' requires an argument" >&2
         exit 1
       fi
       if [ "$1" == system ]; then
@@ -240,7 +246,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --extra-build-arg)
       if [ -z "$1" ]; then
-        echo "$0: '--extra-build-arg' requires an argument" >&2
+        echo "nixos-alter: '--extra-build-arg' requires an argument" >&2
         exit 1
       fi
       extraBuildArgs+=("$1")
@@ -248,7 +254,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --include|--max-jobs)
       if [ -z "$1" ]; then
-        echo "$0: '$arg' requires an argument" >&2
+        echo "nixos-alter: '$arg' requires an argument" >&2
         exit 1
       fi
       extraBuildArgs+=("$arg" "$1")
@@ -256,7 +262,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --channel)
       if [ -z "$1" ]; then
-        echo "$0: '--channel' requires an argument" >&2
+        echo "nixos-alter: '--channel' requires an argument" >&2
         exit 1
       fi
       extraBuildArgs+=("--include" "nixpkgs=$(nix-instantiate --find-file "$1")")
@@ -267,7 +273,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --generation)
       if [ -z "$1" ]; then
-        echo "$0: '--generation' requires an argument" >&2
+        echo "nixos-alter: '--generation' requires an argument" >&2
         exit 1
       fi
       pathToConfig=$(realpath "$profile-$1-link")
@@ -275,7 +281,7 @@ while [ "$#" -gt 0 ]; do
       ;;
     --raw)
       if [ -z "$1" ]; then
-        echo "$0: '--raw' requires an argument" >&2
+        echo "nixos-alter: '--raw' requires an argument" >&2
         exit 1
       fi
       pathToConfig="$(realpath "$1")"
@@ -311,7 +317,7 @@ while [ "$#" -gt 0 ]; do
       showHelp
       ;;
     *)
-      echo "$0: Argument '$arg' is not recognised" >&2
+      echo "nixos-alter: Argument '$arg' is not recognised" >&2
       exit 1
       ;;
   esac
@@ -327,8 +333,9 @@ if [ "$delete" -eq 1 ]; then
   exit 0
 fi
 
-if [ "$boot" -eq 0 ] && [ "$activate" -eq 0 ] && [ "$modify" -eq 0 ] && [ "$link" -eq 0 ]; then
-  echo "warning: None of --boot, --activate, --modify-profile, and --link specified" >&2
+if [ "$boot" -eq 0 ] && [ "$activate" -eq 0 ] && [ "$modify" -eq 0 ] && [ "$link" -eq 0 ] && ! [ "$force" -eq 1 ]; then
+  echo "error: None of --boot, --activate, --modify-profile, --link, and --delete-profile specified. Set --force to ignore. Run 'nixos-alter --help' for more information" >&2
+  exit 1
 fi
 
 if [ -z "$pathToConfig" ]; then
